# (Optional) Configure and deploy workload on keswick through firstboot:
# - Configure: Can override worker VM CPU/RAM sizing
# - Deploy: Can create k8s workload/apps/objects directly
# - Deploy: Can provide k8s workload/apps/objects through GitOps

# -->8--
# ----------------------------------------------------------------------------
# Sample: Optional: Uncomment and change the CPU/memory allocated to worker VM
# ----------------------------------------------------------------------------
#---
#apiVersion: vmoperator.vmware.com/v1alpha1
#kind: VirtualMachineClass
#metadata:
#  name: best-effort-keswick-small
#  # No resource requests/reservations.
#  # Memory overcommit possible.
#spec:
#  hardware:
#    cpus: 4  # Must be power of 2, e.g. 1, 2, 4, ...
#    memory: 6Gi
# ----------------------------------------------------------------------------
# --8<--

# -->8--
#-----------------------------------------------------------------------------
# A sample Keswick config file that shows how to specify workload (to be run
# on Keswick Kubernetes cluster). This example runs nginx web server with
# 2-Pod ReplicaSet, pulling `bitnami/nginx` container image from hub.docker.com
# container registry, exposed throgh a `NodePort` type Kubernetes Service.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
     containers:
      - name: nginx
        image: bitnami/nginx:1.21
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8080
      nodePort: 30080
---
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: keswick-host-config
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
        "system": {
          "system_time": {
            "enabled": true,
            "protocol": "NTP",
            "ntp_config": {
              "server": [{
                  "hostname": "0.vmware.pool.ntp.org",
                  "command": "SERVER"
                },
                {
                  "hostname": "1.vmware.pool.ntp.org",
                  "command": "SERVER"
                }
              ]
            }
          }
        }
      }
    }
# ----------------------------------------------------------------------------
# --8<--

# -->8--
# ----------------------------------------------------------------------------
# Sample: Optional: Inject workload through gitops
# Must provide:
# - a k8s `Secret` for git repo access
# - a flux `GitRepository` custom resource for git repo (also referring
#   above Secret object)
# - a flux `Kustomization` custom resource for applying yamls in above git
#   repo into Keswick k8s cluster (referring to above GitRepository object)
# Replace all strings with `replace-with-...` values in below yamls.
# ----------------------------------------------------------------------------
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: flux-system
#  namespace: flux-system
#stringData:
#  password: replace-with-some-access-token
#  username: replace-with-some-username
#---
#apiVersion: source.toolkit.fluxcd.io/v1
#kind: GitRepository
#metadata:
#  name: flux-system
#  namespace: flux-system
#spec:
#  interval: 1m0s
#  ref:
#    branch: replace-with-some-branch-name
#  secretRef:
#    name: flux-system
#  url: https://git.com/replace-with-some-username/replace-with-some-reponame.git
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: flux-system
#  namespace: flux-system
#spec:
#  interval: 1m0s
#  path: ./
#  prune: true
#  wait: false
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
# ----------------------------------------------------------------------------
# --8<--
